services:
  - type: web
    name: backend-api
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
